[project]
name = "tf-cartpole"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium>=1.2.0",
    "numpy>=2.1.3",
    "pygame>=2.6.1",
    "tensorflow>=2.19.0",
]
